=== Smolky/xml-stack/topbands.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
   <!-- Top 10 Bands. Contains a list of bands -->
   <xs:element name="bands">
      <xs:complexType>
         <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="10" ref="band" />
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <!-- A band element. Formed by members -->
   <xs:element name="band">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="title" />
            <xs:element ref="year" />
            <xs:element ref="members" minOccurs="0" />
         </xs:sequence>
         <!-- A band can be active or not -->
         <xs:attribute name="active">
            <xs:simpleType>
               <xs:restriction base="xs:boolean" />
            </xs:simpleType>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <!-- Members -->
   <xs:element name="members">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="member" minOccurs="0" maxOccurs="30" />
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <!-- Member -->
   <xs:element name="member">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="fullname" />
            <xs:element ref="instruments" />
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <!-- Instruments -->
   <xs:element name="instruments">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="instrument" minOccurs="0" maxOccurs="10" />
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <!-- Elements -->
   <xs:element name="title" type="xs:string" />
   <xs:element name="fullname" type="xs:string" />
   <xs:element name="instrument" type="xs:string" />
   <xs:element name="year" type="xs:positiveInteger" />
</xs:schema>

=== Smolky/xml-stack/topbands2-with-xsl.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="topbands2.xsl"?>
<bands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="topbands.xsd">
   <band active="true">
      <title>Angra</title>
      <year>1985</year>
      <members>
         <member>
            <fullname>Fabio Lione</fullname>
            <instruments>
               <instrument>Voice</instrument>
            </instruments>
         </member>
      </members>
   </band>
   <band>
      <title>Rage</title>
      <year>2002</year>
   </band>
   <band>
      <title>Red Hot Chili Peppers</title>
      <year>1980</year>
   </band>
   <band>
      <title>The Beatles</title>
      <year>1958</year>
   </band>
   <band>
      <title>Christofer Cross</title>
      <year>1970</year>
   </band>
</bands>

=== Smolky/xml-stack/topbands2-with-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<bands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="topbands.xsd">
   <band active="true">
      <title>Angra</title>
      <year>1985</year>
   </band>
   <band>
      <title>Rage</title>
      <year>2002</year>
   </band>
   <band>
      <title>Red Hot Chili Peppers</title>
      <year>1980</year>
   </band>
   <band>
      <title>The Beatles</title>
      <year>1958</year>
   </band>
   <band>
      <title>Christofer Cross</title>
      <year>1970</year>
   </band>
</bands>

=== Smolky/xml-stack/topbands1-with-xsl.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="topbands1.xsl"?>
<bands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="topbands.xsd">
   <band active="true">
      <title>Angra</title>
      <year>1985</year>
      <members>
         <member>
            <fullname>Fabio Lione</fullname>
            <instruments>
               <instrument>Voice</instrument>
            </instruments>
         </member>
         <member>
            <fullname>Rafael Bittencourt</fullname>
            <instruments>
               <instrument>Guitar</instrument>
            </instruments>
         </member>
         <member>
            <fullname>Marcelo Barbosa</fullname>
            <instruments>
               <instrument>Guitar</instrument>
            </instruments>
         </member>
         <member>
            <fullname>Felipe Andreoli</fullname>
            <instruments>
               <instrument>Bass Guitar</instrument>
            </instruments>
         </member>
         <member>
            <fullname>Aquiles Priester</fullname>
            <instruments>
               <instrument>Drums</instrument>
            </instruments>
         </member>
      </members>
   </band>
   <band>
      <title>Nirvana</title>
      <year>1980</year>
      <members>
         <member>
            <fullname>Kurt Cobain</fullname>
            <instruments>
               <instrument>Voice</instrument>
               <instrument>Guitar</instrument>
            </instruments>
         </member>
         <member>
            <fullname>Krist Anthony Novoselic</fullname>
            <instruments>
               <instrument>Bass</instrument>
            </instruments>
         </member>
         <member>
            <fullname>Dave Grohl</fullname>
            <instruments>
               <instrument>Drums</instrument>
            </instruments>
         </member>
      </members>
   </band>
</bands>
